name: Generate Snake Contribution Grid
on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: FahadCloudOps
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push the Snk output
        uses: actions/upload-artifact@v2
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.svg
